/* Feedback, échanges et propositions : stockage local respectueux de la vie privée. */
(() => {
  'use strict';
  const $=s=>document.querySelector(s), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const KEYS={feedback:'oceanbuddy_feedback_v1',posts:'oceanbuddy_community_v1',custom:'oceanbuddy_custom_spots_v1'};
  const read=(key,fallback=[])=>{try{const v=JSON.parse(localStorage.getItem(key)||'null');return Array.isArray(v)?v:fallback}catch(_){return fallback}};
  const write=(key,v)=>{try{localStorage.setItem(key,JSON.stringify(v));return true}catch(_){toast('Enregistrement indisponible sur cet appareil.');return false}};
  let feedback=read(KEYS.feedback),posts=read(KEYS.posts),custom=read(KEYS.custom);
  const slug=s=>String(s).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,45);
  function customSpots(){return custom.filter(s=>s&&s.id&&s.name&&s.coords&&Number.isFinite(+s.coords.lat)&&Number.isFinite(+s.coords.lon));}
  function registerCustom(){customSpots().forEach(s=>{if(!SPOTS.some(x=>x.id===s.id)){SPOTS.push(s);COORDS[s.id]=s.coords;SPOT_WORLD[s.id]=s.world||'eu';}})}
  registerCustom();
  function stars(value){return [1,2,3,4,5].map(n=>`<button type="button" class="feedback-star${n<=value?' on':''}" data-star="${n}" aria-label="${n} sur 5">★</button>`).join('');}
  function feedbackFor(type,id){return feedback.filter(x=>x.type===type&&x.id===id);}
  function average(type,id){const list=feedbackFor(type,id);return list.length?(list.reduce((a,x)=>a+(+x.rating||0),0)/list.length).toFixed(1):'—';}
  function mountSpot(id){
    const host=$('#detail .detail-body');if(!host||!id)return;
    let box=$('#spotFeedback');if(!box){box=document.createElement('section');box.id='spotFeedback';box.className='community-feedback';host.append(box);}
    const list=feedbackFor('spot',id);box.innerHTML=`<div class="community-section-head"><span class="community-kicker">TON RETOUR COMPTE</span><h3>Partager ce spot</h3><span class="feedback-average">${average('spot',id)} ★ · ${list.length} avis</span></div><p class="community-muted">Aide les prochains explorateurs : conditions vécues, accès et ambiance du jour.</p><form class="feedback-form" data-feedback-type="spot" data-feedback-id="${esc(id)}"><div class="feedback-stars" role="radiogroup" aria-label="Note du spot">${stars(0)}</div><textarea name="text" maxlength="500" required placeholder="Ton expérience en quelques mots…"></textarea><button class="community-primary" type="submit">Publier mon retour</button></form>${list.slice(-3).reverse().map(x=>`<article class="feedback-item"><div>${stars(+x.rating||0)}</div><p>${esc(x.text)}</p><small>${esc(x.author||'Explorateur')} · ${esc(x.date||'récemment')}</small></article>`).join('')}`;
  }
  const postCard=p=>'<article class="community-post"><div class="post-avatar">'+esc((p.author||'E').slice(0,1).toUpperCase())+'</div><div><b>'+esc(p.author||'Explorateur')+'</b><small>'+esc(p.date||'récemment')+'</small><p>'+esc(p.text)+'</p>'+(p.spot?'<span class="post-tag">'+esc(p.spot)+'</span>':'')+'</div></article>';
  function render(){
    const host=$('#communityContent');if(!host)return;
    let trip=null;try{const activeTrip=window.OceanTrips?.route()?.selected,data=JSON.parse(localStorage.getItem('oceanbuddy_trips_v1')||'{"trips":[]}');trip=activeTrip&&data.trips?.find(x=>x.id===activeTrip)}catch(_){trip=null}
    const feed=posts.length?posts.slice(-12).reverse().map(postCard).join(''):'<p class="community-empty">Le fil est encore calme. Sois le premier à partager une expérience.</p>';
    const tripBox=trip?'<p class="community-muted">'+esc(trip.name)+' · '+trip.steps.length+' spot'+(trip.steps.length>1?'s':'')+'</p><form class="feedback-form" data-feedback-type="trip" data-feedback-id="'+esc(trip.id)+'"><div class="feedback-stars">'+stars(0)+'</div><textarea name="text" maxlength="500" required placeholder="Ce qui a rendu ton itinéraire réussi…"></textarea><button class="community-primary" type="submit">Partager mon retour</button></form>':'<p class="community-muted">Ouvre un voyage dans Surf trips pour partager ton retour ici.</p>';
    const n=customSpots().length;
    host.innerHTML='<div class="community-hero"><span class="community-kicker">OCEAN BUDDY · ENSEMBLE</span><h1>La communauté<br><b>partage le large.</b></h1><p>Conseils de terrain, récits de sessions et nouveaux spots proposés par les explorateurs.</p></div><div class="community-grid"><section class="community-panel"><div class="community-section-head"><div><span class="community-kicker">LE FIL DU LARGE</span><h2>Échanger avec les autres</h2></div></div><form id="communityPostForm" class="post-form"><input name="author" maxlength="30" placeholder="Ton prénom" required><textarea name="text" maxlength="600" placeholder="Raconte ta dernière session ou donne un conseil…" required></textarea><button class="community-primary" type="submit">Publier dans le fil</button></form><div class="community-feed">'+feed+'</div></section><aside class="community-side"><section class="community-panel"><span class="community-kicker">TON AVIS</span><h2>Évaluer un surf trip</h2>'+tripBox+'</section><section class="community-panel"><span class="community-kicker">CARTE PARTICIPATIVE</span><h2>Ajouter un spot</h2><p class="community-muted">Tu connais une mise à l’eau, une crique ou un site de plongée absent du catalogue ?</p><button class="community-primary" data-open-custom>Proposer un spot +</button><p class="community-note">Les propositions restent sur cet appareil jusqu’à validation éditoriale.</p></section><section class="community-panel"><span class="community-kicker">TES PROPOSITIONS</span><p class="community-muted">'+n+' spot'+(n>1?'s':'')+' ajouté'+(n>1?'s':'')+' par toi.</p></section></aside></div>';
  }
  function customDialog(){
    const d=document.createElement('dialog');d.className='community-dialog';const sportOptions=SPORTS.map(s=>'<option value="'+esc(s.id)+'">'+esc(s.label)+'</option>').join('');d.innerHTML=`<button class="dialog-x" data-close aria-label="Fermer">×</button><span class="community-kicker">CARTE PARTICIPATIVE</span><h2>Ajouter ton spot</h2><p>Donne un nom et une position approximative. Tu pourras le retrouver dans tes cartes.</p><form id="customSpotForm"><label>Nom du spot<input name="name" maxlength="80" required placeholder="La crique secrète"></label><label>Pays / région<input name="loc" maxlength="100" required placeholder="Bretagne, France"></label><div class="custom-coords"><label>Latitude<input name="lat" type="number" step="any" min="-90" max="90" required placeholder="48.20"></label><label>Longitude<input name="lon" type="number" step="any" min="-180" max="180" required placeholder="-4.50"></label></div><label>Activité<select name="sport">${sportOptions}</select></label><label>Description<textarea name="desc" maxlength="400" placeholder="Pourquoi ce spot vaut le détour ?"></textarea></label><button class="community-primary" type="submit">Ajouter à ma carte</button></form>`;document.body.append(d);d.showModal();d.addEventListener('click',e=>{if(e.target===d||e.target.closest('[data-close]'))d.close()});d.querySelector('form').onsubmit=e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target)),id='custom-'+slug(f.name)+'-'+Date.now().toString(36),world=typeof spotWorld!=='undefined'&&spotWorld&&spotWorld!=='all'?spotWorld:'eu',s={id,name:f.name.trim(),loc:f.loc.trim(),world,coords:{lat:+f.lat,lon:+f.lon},sports:[f.sport],level:'variable',desc:f.desc.trim()||'Spot proposé par la communauté Ocean Buddy.',dangers:[],tip:'Vérifie les règles locales et les conditions avant toute sortie.',sky:'#c9dfed',sky2:'#8bbbd7',sea:'#2c789b',sea2:'#17486e',wind:'—',swell:'—',temp:'—',tide:'—',danger:0,custom:true};custom.push(s);write(KEYS.custom,custom);SPOTS.push(s);COORDS[s.id]=s.coords;SPOT_WORLD[s.id]=world;d.close();render();toast('Spot ajouté à ta carte 🌊');if(typeof renderSpots==='function'){renderSpots();renderMap?.(true)}};
  }
  document.addEventListener('click',e=>{const b=e.target.closest('[data-star]');if(b){const form=b.closest('form');form.dataset.rating=b.dataset.star;form.querySelectorAll('[data-star]').forEach(x=>x.classList.toggle('on',+x.dataset.star<=+b.dataset.star));}if(e.target.closest('[data-open-custom]'))customDialog();});
  document.addEventListener('submit',e=>{const f=e.target;if(f.matches('[data-feedback-type]')){e.preventDefault();const text=f.elements.text.value.trim(),rating=+f.dataset.rating||0;if(!rating||!text){toast('Choisis une note et écris quelques mots.');return}feedback.push({type:f.dataset.feedbackType,id:f.dataset.feedbackId,rating,text,author:localStorage.getItem('oceanbuddy_name')||'Explorateur',date:new Date().toLocaleDateString('fr-FR',{day:'numeric',month:'short',year:'numeric'})});if(write(KEYS.feedback,feedback)){toast('Merci pour ton retour 💙');if(f.dataset.feedbackType==='spot')mountSpot(f.dataset.feedbackId);else render()}}if(f.id==='communityPostForm'){e.preventDefault();const v=Object.fromEntries(new FormData(f));posts.push({author:v.author.trim(),text:v.text.trim(),date:new Date().toLocaleDateString('fr-FR',{day:'numeric',month:'short'}),spot:typeof currentSpot!=='undefined'&&currentSpot?SPOTS.find(s=>s.id===currentSpot)?.name.split(' — ')[0]:''});if(write(KEYS.posts,posts)){f.reset();render();toast('Message publié dans le fil 🌊')}}});
  window.OceanCommunity={render,mountSpot};
  window.addEventListener('ocean:navigate',e=>{if(e.detail==='community')render()});
  render();
})();
