from pathlib import Path
import html,json
root=Path(__file__).resolve().parent.parent
meta=json.loads((root/'assets/photos/sources.json').read_text())
labels={'fr':'France','eu':'Europe','af':'Afrique','na':'Amérique du Nord','sa':'Amérique du Sud','as':'Asie','oc':'Océanie','hero':'Accueil · vague'}
cards=[]
for id,label in labels.items():
 p=meta[id];source=html.escape(p['source'],quote=True);author=html.escape(p['author']);lic=html.escape(p['license']);place=html.escape(p['place'])
 license_url='https://unsplash.com/license' if id=='hero' else p.get('metadata',{}).get('LicenseUrl',{}).get('value','https://creativecommons.org/publicdomain/zero/1.0/')
 cards.append(f'<article><img src="assets/photos/{id}.jpg" alt="{place}" loading="lazy"><div><small>{label}</small><h2>{place}</h2><p>Photographie : {author}</p><a href="{source}" target="_blank" rel="noopener">Voir la photo originale ↗</a><a href="{html.escape(license_url,quote=True)}" target="_blank" rel="noopener">{lic} ↗</a></div></article>')
page='''<!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Photographies — Ocean Buddy</title><style>
*{box-sizing:border-box}body{margin:0;background:#071f2c;color:#e6f7fc;font:15px/1.7 system-ui,sans-serif}main{max-width:1040px;margin:auto;padding:35px 25px 70px}a{color:#5ee4ca;text-underline-offset:4px}h1{font-size:clamp(32px,6vw,54px);line-height:1.1;margin:32px 0 18px}header p{color:#b4d0db;max-width:760px}section{display:grid;grid-template-columns:1fr 1fr;gap:22px;margin-top:30px}article{background:#113543;border:1px solid #335d6b;border-radius:18px;overflow:hidden}article img{width:100%;height:230px;object-fit:cover;display:block}article div{padding:22px}article small{color:#ff9866;font-weight:700;text-transform:uppercase;letter-spacing:1px}article h2{font-size:21px;line-height:1.4;margin:9px 0}article p{font-size:13px;color:#b9d4de}article a{font-size:12px;margin-right:20px;display:inline-block}footer{margin-top:35px;color:#91b4c2;font-size:13px}@media(max-width:600px){section{grid-template-columns:1fr}}
</style></head><body><main><a href="index.html">← Revenir à Ocean Buddy</a><header><h1>De vrais lieux.<br>De vrais regards.</h1><p>Les sept destinations et la vague de l’accueil sont des photographies de photographes, utilisées sous les licences indiquées. Elles sont présentées sans transformation générative ; leur cadrage et le voile de contraste varient selon l’écran.</p></header><section>'''+''.join(cards)+'''</section><footer>Sources des destinations : Wikimedia Commons. Les autres photos des fiches de spots portent leurs propres crédits dans l’application. Poulpy et les illustrations de l’aquarium sont des éléments illustrés de l’identité Ocean Buddy. Les images sont disponibles en résolution adaptée à l’écran ; les conditions de leur licence restent applicables.</footer></main></body></html>'''
(root/'photos.html').write_text(page)
